---
## Version-specific settings that override the values in cfg/config.yaml

node:
  kubelet:
    defaultkubeconfig: "/etc/kubernetes/ssl/kubecfg-kube-node.yaml"
    defaultcafile: "/etc/kubernetes/ssl/kube-ca.pem"
    bins:
      - "containerd"
      - "hyperkube kubelet"
      - "kubelet"

  proxy:
    defaultkubeconfig: "/etc/kubernetes/ssl/kubecfg-kube-proxy.yaml"
